### ISSUE TITLE
Could not create task of type 'ShadowJar'

### ISSUE THREAD

**Issue by rahulsom** [johnrengelman/shadow#254]
### Shadow Version
1.2.3

### Gradle Version
2.9

### Expected Behavior
Running `./gradlew` works

### Actual Behavior
I get this error
```
$ ./gradlew tasks --profile        
Parallel execution is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/rahul/src/Clouseau/build.gradle' line: 20

* What went wrong:
An exception occurred applying plugin request [id: 'com.github.johnrengelman.shadow', version: '1.2.3']
> Failed to apply plugin [class 'com.github.jengelman.gradle.plugins.shadow.ShadowJavaPlugin']
   > Could not create task of type 'ShadowJar'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.129 secs
```

### Gradle Build Script(s)
```
import org.gradle.internal.jvm.Jvm

buildscript {
  repositories {
    maven { url "http://ti-nexus.rsc.humad.com:8081/nexus/content/groups/public" }
    mavenCentral()
    jcenter()
    maven { url 'https://plugins.gradle.org/m2/' }
  }
  dependencies {
    classpath 'com.bertramlabs.plugins:less-asset-pipeline:2.6.4'
  }
}

plugins {
  id "com.craigburke.karma" version "1.4.3"
  id "com.craigburke.bower-installer" version "2.5.1"
  id "com.bertramlabs.asset-pipeline" version "2.6.9"
  id "io.ratpack.ratpack-groovy" version "1.2.0"
  id "com.github.johnrengelman.shadow" version "1.2.3"
  id "com.github.rahulsom.linters" version "0.1"
}

apply plugin: 'maven'
apply plugin: 'idea'
apply from: 'gradle/bower.gradle'
apply from: 'gradle/testing.gradle'
apply from: 'gradle/linter.gradle'

def jvm = Jvm.current()
if (!jvm.javaVersion.isJava8Compatible()) {
  throw new Error("Current Java version is ${jvm}. It is not Java 8 compatible.")
}

repositories {
  mavenLocal()
  maven { url "http://ti-nexus.rsc.humad.com:8081/nexus/content/groups/public" }
  mavenCentral()
  jcenter()
  maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
}

dependencies {
  runtime 'org.slf4j:slf4j-simple:1.7.12'

  compile ratpack.dependency('guice')
  compile 'com.bertramlabs.plugins:ratpack-asset-pipeline:2.6.4'
  compile 'com.bertramlabs.plugins:less-asset-pipeline:2.6.4'
  compile 'com.github.rahulsom:rp-config:0.1-SNAPSHOT'
  compile 'com.github.rahulsom:rp-i18n-json:0.1-SNAPSHOT'
  compile 'net.alchim31:livereload-jvm:0.2.0'

  assets 'com.craigburke.angular:angular-annotate-asset-pipeline:2.4.0'
}

node {
  version = '4.2.2'
}

def buildNumber = System.getenv("BUILD_NUMBER") ?: "unknown"

shadowJar {
  baseName = 'Clouseau'
  classifier = ''
}

uploadShadow {
  repositories {
    mavenDeployer {
      repository(url: "http://ti-nexus.rsc.humad.com:8081/nexus/content/repositories/eng-releases") {
        authentication(...)
      }
      pom.version = "1.$buildNumber"
      pom.artifactId = "Clouseau"
      pom.groupId = "com.transcendinsights"
    }
  }
}

run {
  jvmArgs '-Dratpack.port=3000'
}

check.dependsOn 'karmaRun'
```

### Content of Shadow JAR (`jar tf <jar file>` - post link to GIST if too long)
```
META-INF/
META-INF/MANIFEST.MF
com/
com/github/
com/github/jengelman/
com/github/jengelman/gradle/
com/github/jengelman/gradle/plugins/
com/github/jengelman/gradle/plugins/shadow/
com/github/jengelman/gradle/plugins/shadow/impl/
com/github/jengelman/gradle/plugins/shadow/impl/RelocatorRemapper.class
com/github/jengelman/gradle/plugins/shadow/internal/
com/github/jengelman/gradle/plugins/shadow/internal/DefaultDependencyFilter$_dependency_closure3.class
com/github/jengelman/gradle/plugins/shadow/internal/DefaultDependencyFilter$_isIncluded_closure5.class
com/github/jengelman/gradle/plugins/shadow/internal/DefaultDependencyFilter$_isIncluded_closure6.class
com/github/jengelman/gradle/plugins/shadow/internal/DefaultDependencyFilter$_resolve_closure1.class
com/github/jengelman/gradle/plugins/shadow/internal/DefaultDependencyFilter$_resolve_closure2.class
com/github/jengelman/gradle/plugins/shadow/internal/DefaultDependencyFilter$_resolve_closure4.class
com/github/jengelman/gradle/plugins/shadow/internal/DefaultDependencyFilter.class
com/github/jengelman/gradle/plugins/shadow/internal/DefaultZipCompressor.class
com/github/jengelman/gradle/plugins/shadow/internal/DependencyFilter.class
com/github/jengelman/gradle/plugins/shadow/internal/gradle111/
com/github/jengelman/gradle/plugins/shadow/internal/gradle111/Gradle111DefaultZipCompressor.class
com/github/jengelman/gradle/plugins/shadow/internal/GradleVersionUtil.class
com/github/jengelman/gradle/plugins/shadow/internal/JavaJarExec.class
com/github/jengelman/gradle/plugins/shadow/internal/StartScriptGenerator$_generateUnixScriptContent_closure1.class
com/github/jengelman/gradle/plugins/shadow/internal/StartScriptGenerator$_generateWindowsScriptContent_closure2$_closure4.class
com/github/jengelman/gradle/plugins/shadow/internal/StartScriptGenerator$_generateWindowsScriptContent_closure2.class
com/github/jengelman/gradle/plugins/shadow/internal/StartScriptGenerator$_getAppHomeRelativePath_closure3.class
com/github/jengelman/gradle/plugins/shadow/internal/StartScriptGenerator.class
com/github/jengelman/gradle/plugins/shadow/internal/ZipCompressor.class
com/github/jengelman/gradle/plugins/shadow/relocation/
com/github/jengelman/gradle/plugins/shadow/relocation/Relocator$1.class
com/github/jengelman/gradle/plugins/shadow/relocation/Relocator.class
com/github/jengelman/gradle/plugins/shadow/relocation/SimpleRelocator.class
com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin$_addArchiveTask_closure11.class
com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin$_addArchiveTask_closure12.class
com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin$_addArchiveTask_closure13.class
com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin$_addCreateScriptsTask_closure4.class
com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin$_addCreateScriptsTask_closure5.class
com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin$_addCreateScriptsTask_closure6.class
com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin$_addCreateScriptsTask_closure7.class
com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin$_addInstallTask_closure10.class
com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin$_addInstallTask_closure8.class
com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin$_addInstallTask_closure9.class
com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin$_addRunTask_closure2.class
com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin$_addRunTask_closure3.class
com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin$_configureDistSpec_closure14$_closure15.class
com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin$_configureDistSpec_closure14$_closure16.class
com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin$_configureDistSpec_closure14.class
com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin$_configureJarMainClass_closure1.class
com/github/jengelman/gradle/plugins/shadow/ShadowApplicationPlugin.class
com/github/jengelman/gradle/plugins/shadow/ShadowBasePlugin.class
com/github/jengelman/gradle/plugins/shadow/ShadowExtension$_closure1.class
com/github/jengelman/gradle/plugins/shadow/ShadowExtension.class
com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin$1.class
com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin$_configureShadowTask_closure1$_closure3.class
com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin$_configureShadowTask_closure1.class
com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin$_configureShadowTask_closure2$_closure4.class
com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin$_configureShadowTask_closure2$_closure5.class
com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin$_configureShadowTask_closure2.class
com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin$ShadowJavaLibrary.class
com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.class
com/github/jengelman/gradle/plugins/shadow/ShadowPlugin$_apply_closure1.class
com/github/jengelman/gradle/plugins/shadow/ShadowPlugin$_apply_closure2.class
com/github/jengelman/gradle/plugins/shadow/ShadowPlugin.class
com/github/jengelman/gradle/plugins/shadow/ShadowStats.class
com/github/jengelman/gradle/plugins/shadow/tasks/
com/github/jengelman/gradle/plugins/shadow/tasks/DefaultInheritManifest$_getEffectiveManifest_closure1.class
com/github/jengelman/gradle/plugins/shadow/tasks/DefaultInheritManifest.class
com/github/jengelman/gradle/plugins/shadow/tasks/InheritManifest.class
com/github/jengelman/gradle/plugins/shadow/tasks/KnowsTask.class
com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction$1.class
com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction$_processTransformers_closure1.class
com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction$ArchiveFileTreeElement.class
com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction$RelativeArchivePath.class
com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction$StreamAction$_isTransformable_closure5.class
com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction$StreamAction$_processArchive_closure1.class
com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction$StreamAction$_processArchive_closure2.class
com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction$StreamAction$_processArchive_closure3.class
com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction$StreamAction$_transform_closure4.class
com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction$StreamAction.class
com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction.class
com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCreateStartScripts.class
com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar$1.class
com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar$2.class
com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar.class
com/github/jengelman/gradle/plugins/shadow/tasks/ShadowSpec.class
com/github/jengelman/gradle/plugins/shadow/transformers/
com/github/jengelman/gradle/plugins/shadow/transformers/ApacheLicenseResourceTransformer.class
com/github/jengelman/gradle/plugins/shadow/transformers/ApacheNoticeResourceTransformer.class
com/github/jengelman/gradle/plugins/shadow/transformers/AppendingTransformer.class
com/github/jengelman/gradle/plugins/shadow/transformers/ComponentsXmlResourceTransformer$1.class
com/github/jengelman/gradle/plugins/shadow/transformers/ComponentsXmlResourceTransformer.class
com/github/jengelman/gradle/plugins/shadow/transformers/DontIncludeResourceTransformer.class
com/github/jengelman/gradle/plugins/shadow/transformers/GroovyExtensionModuleTransformer$_transform_closure1$_closure2.class
com/github/jengelman/gradle/plugins/shadow/transformers/GroovyExtensionModuleTransformer$_transform_closure1$_closure3.class
com/github/jengelman/gradle/plugins/shadow/transformers/GroovyExtensionModuleTransformer$_transform_closure1$_closure4.class
com/github/jengelman/gradle/plugins/shadow/transformers/GroovyExtensionModuleTransformer$_transform_closure1.class
com/github/jengelman/gradle/plugins/shadow/transformers/GroovyExtensionModuleTransformer.class
com/github/jengelman/gradle/plugins/shadow/transformers/IncludeResourceTransformer.class
com/github/jengelman/gradle/plugins/shadow/transformers/ManifestResourceTransformer.class
com/github/jengelman/gradle/plugins/shadow/transformers/PropertiesFileTransformer$_modifyOutputStream_closure2.class
com/github/jengelman/gradle/plugins/shadow/transformers/PropertiesFileTransformer$_transform_closure1.class
com/github/jengelman/gradle/plugins/shadow/transformers/PropertiesFileTransformer.class
com/github/jengelman/gradle/plugins/shadow/transformers/ServiceFileTransformer$_closure1.class
com/github/jengelman/gradle/plugins/shadow/transformers/ServiceFileTransformer$_modifyOutputStream_closure4.class
com/github/jengelman/gradle/plugins/shadow/transformers/ServiceFileTransformer$_transform_closure2$_closure5.class
com/github/jengelman/gradle/plugins/shadow/transformers/ServiceFileTransformer$_transform_closure2.class
com/github/jengelman/gradle/plugins/shadow/transformers/ServiceFileTransformer$_transform_closure3.class
com/github/jengelman/gradle/plugins/shadow/transformers/ServiceFileTransformer$ServiceStream.class
com/github/jengelman/gradle/plugins/shadow/transformers/ServiceFileTransformer.class
com/github/jengelman/gradle/plugins/shadow/transformers/Transformer.class
com/github/jengelman/gradle/plugins/shadow/transformers/XmlAppendingTransformer$1.class
com/github/jengelman/gradle/plugins/shadow/transformers/XmlAppendingTransformer$_transform_closure1.class
com/github/jengelman/gradle/plugins/shadow/transformers/XmlAppendingTransformer$_transform_closure2.class
com/github/jengelman/gradle/plugins/shadow/transformers/XmlAppendingTransformer.class
com/github/jengelman/gradle/plugins/shadow/internal/unixStartScript.txt
com/github/jengelman/gradle/plugins/shadow/internal/windowsStartScript.txt
META-INF/gradle-plugins/
META-INF/gradle-plugins/com.github.johnrengelman.shadow.properties
shadow-version.txt
shadowBanner.txt
LICENSE
NOTICE
```

**Comment by johnrengelman** [comment]
How are you getting a shadow Jar generated if Gradle errors on applying shadow?
Can you run `gradle tasks --profile -s` and post the full stack trace?

**Comment by johnrengelman** [comment]
Can you run from a newer version of Gradle? 2.9 is really old.

**Comment by rahulsom** [comment]
This is still 2.9

```
* Exception is:
org.gradle.api.plugins.InvalidPluginException: An exception occurred applying plugin request [id: 'com.github.johnrengelman.shadow', version: '1.2.3']
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:178)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:130)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:126)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:38)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:25)
	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:496)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:87)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
	at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:125)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:122)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [class 'com.github.jengelman.gradle.plugins.shadow.ShadowJavaPlugin']
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:160)
	at org.gradle.api.internal.plugins.DefaultPluginManager.addImperativePlugin(DefaultPluginManager.java:67)
	at org.gradle.api.internal.plugins.DefaultPluginManager.addImperativePlugin(DefaultPluginManager.java:73)
	at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultPluginContainer.java:60)
	at org.gradle.api.plugins.PluginContainer$apply.call(Unknown Source)
	at com.github.jengelman.gradle.plugins.shadow.ShadowPlugin$_apply_closure1.doCall(ShadowPlugin.groovy:14)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
	at org.gradle.internal.Actions$FilteredAction.execute(Actions.java:202)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:110)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:115)
	at org.gradle.api.internal.DefaultDomainObjectCollection.withType(DefaultDomainObjectCollection.java:126)
	at org.gradle.api.DomainObjectCollection$withType.call(Unknown Source)
	at com.github.jengelman.gradle.plugins.shadow.ShadowPlugin.apply(ShadowPlugin.groovy:13)
	at com.github.jengelman.gradle.plugins.shadow.ShadowPlugin.apply(ShadowPlugin.groovy)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
	at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:44)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:144)
	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:112)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator$5.run(DefaultPluginRequestApplicator.java:132)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:166)
	... 57 more
Caused by: org.gradle.api.tasks.TaskInstantiationException: Could not create task of type 'ShadowJar'.
	at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:123)
	at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:118)
	at org.gradle.api.internal.AbstractTask.injectIntoNewInstance(AbstractTask.java:143)
	at org.gradle.api.internal.project.taskfactory.TaskFactory.create(TaskFactory.java:118)
	at org.gradle.api.internal.project.taskfactory.TaskFactory.createTask(TaskFactory.java:77)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory.createTask(AnnotationProcessingTaskFactory.java:100)
	at org.gradle.api.internal.project.taskfactory.DependencyAutoWireTaskFactory.createTask(DependencyAutoWireTaskFactory.java:39)
	at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:62)
	at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:97)
	at org.gradle.api.tasks.TaskContainer$create.call(Unknown Source)
	at com.github.jengelman.gradle.plugins.shadow.ShadowJavaPlugin.configureShadowTask(ShadowJavaPlugin.groovy:40)
	at com.github.jengelman.gradle.plugins.shadow.ShadowJavaPlugin.apply(ShadowJavaPlugin.groovy:35)
	at com.github.jengelman.gradle.plugins.shadow.ShadowJavaPlugin.apply(ShadowJavaPlugin.groovy)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
	at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:44)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:144)
	... 76 more
Caused by: java.lang.NoClassDefFoundError: org/apache/tools/zip/ZipOutputStream
	at org.gradle.api.tasks.bundling.Jar.$getStaticMetaClass(Jar.groovy)
	at org.gradle.api.tasks.bundling.Jar.<init>(Jar.groovy)
	at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar.<init>(ShadowJar.java:42)
	at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar_Decorated.<init>(Unknown Source)
	at org.gradle.api.internal.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:48)
	at org.gradle.api.internal.ClassGeneratorBackedInstantiator.newInstance(ClassGeneratorBackedInstantiator.java:36)
	at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:121)
	... 91 more
Caused by: java.lang.ClassNotFoundException: org.apache.tools.zip.ZipOutputStream
	... 98 more
```

I guess I just need to add ant as a dependency then.
It appears it works with Gradle 3.0 though. I'll take that route. Thanks!
