### ISSUE TITLE
Broken on Gradle 2.5 and 2.6

### ISSUE THREAD

**Issue by kensipe** [johnrengelman/shadow#154]
A build with shadow was working gradle 2.4.   an upgrade to 2.5 or 2.6 results in the following:

Caused by: java.lang.NoClassDefFoundError: org.gradle.mvn3.org.codehaus.plexus.util.IOUtil

**Comment by centic9** [comment]
Seemingly a duplicate of #147 and #148

**Comment by johnrengelman** [comment]
@kensipe are you using the latest `1.2.2` release?
